## NCAA Bracket Model — Feature Engineering

In [154]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [155]:
def show_columns(df):
    for col in df.columns:
        print(col)

### Step 1: Build Team Season Averages

In [156]:
season_stats = pd.read_csv("../data/raw/MRegularSeasonDetailedResults.csv")
season_stats.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [157]:
show_columns(season_stats)

Season
DayNum
WTeamID
WScore
LTeamID
LScore
WLoc
NumOT
WFGM
WFGA
WFGM3
WFGA3
WFTM
WFTA
WOR
WDR
WAst
WTO
WStl
WBlk
WPF
LFGM
LFGA
LFGM3
LFGA3
LFTM
LFTA
LOR
LDR
LAst
LTO
LStl
LBlk
LPF

In [158]:
winners = season_stats[['Season', 'WTeamID', 'WScore', 'LScore', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF']]
winners.rename(columns={'WTeamID': 'TeamID', 'WScore': 'Score', 'LScore': 'OppScore', 'WFGM': 'FGM', 'WFGA': 'FGA', 'WFGM3': 'FGM3', 'WFGA3': 'FGA3', 'WFTM': 'FTM', 'WFTA': 'FTA', 'WAst': 'Ast', 'WTO': 'TO', 'WStl': 'Stl', 'WBlk': 'Blk', 'WPF': 'PF'}, inplace=True)
winners['Win'] = 1
winners.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,1

In [159]:
losers = season_stats[['Season', 'LTeamID', 'LScore', 'WScore', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']]
losers.rename(columns={'LTeamID': 'TeamID', 'LScore': 'Score', 'WScore': 'OppScore', 'LFGM': 'FGM', 'LFGA': 'FGA', 'LFGM3': 'FGM3', 'LFGA3': 'FGA3', 'LFTM': 'FTM', 'LFTA': 'FTA', 'LAst': 'Ast', 'LTO': 'TO', 'LStl': 'Stl', 'LBlk': 'Blk', 'LPF': 'PF'}, inplace=True)
losers['Win'] = 0
losers.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1328,62,68,22,53,2,10,16,22,8,18,9,2,20,0
1,2003,1393,63,70,24,67,6,24,9,20,7,12,8,6,16,0
2,2003,1437,61,73,22,73,3,26,14,23,9,12,2,5,23,0
3,2003,1457,50,56,18,49,6,22,8,15,9,19,4,3,23,0
4,2003,1208,71,77,24,62,6,16,17,27,12,10,7,1,14,0

In [160]:
team_stats = pd.concat([winners, losers], ignore_index=True)
team_stats.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,1

In [161]:
# Verifying the proper amount of rows
print(f"Number of rows in winners: {len(winners)}\nNumber of rows in losers: {len(losers)}\nTotal rows in team_stats: {len(team_stats)}")
if len(winners) + len(losers) == len(team_stats) and len(season_stats) * 2 == len(team_stats):
    print("The number of rows in team_stats is correct.")

Number of rows in winners: 118882
Number of rows in losers: 118882
Total rows in team_stats: 237764
The number of rows in team_stats is correct.

In [162]:
season_averages = team_stats.groupby(['Season', 'TeamID']).mean().reset_index().sort_values(by=['Season', 'TeamID'])    
season_averages.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1102,57.250000,57.000000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,13.000000,11.428571,5.964286,1.785714,18.750000,0.428571
1,2003,1103,78.777778,78.148148,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,15.222222,12.629630,7.259259,2.333333,19.851852,0.481481
2,2003,1104,69.285714,65.000000,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,12.107143,13.285714,6.607143,3.785714,18.035714,0.607143
3,2003,1105,71.769231,76.653846,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,14.538462,18.653846,9.307692,2.076923,20.230769,0.269231
4,2003,1106,63.607143,63.750000,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,11.678571,17.035714,8.357143,3.142857,18.178571,0.464286

In [163]:
season_averages.shape

(7981, 16)

In [164]:
checkwin = season_averages[(season_averages['Win'] < 0) | (season_averages['Win'] > 1)]
if len(checkwin) > 0:
    print("There are invalid values in the 'Win' column.")
else:
    print("All values in the 'Win' column are valid (0 or 1).")

All values in the 'Win' column are valid (0 or 1).

### Step 2: Clean Seed Data

In [165]:
seeds = pd.read_csv("../data/raw/MNCAATourneySeeds.csv")
seeds.head()

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [166]:
seed_clean = seeds.copy()
seed_clean['Seed'] = seed_clean['Seed'].str.replace(r'[a-zA-Z]', '', regex=True).astype(int)
seed_clean.head()

   Season  Seed  TeamID
0    1985     1    1207
1    1985     2    1210
2    1985     3    1228
3    1985     4    1260
4    1985     5    1374

In [167]:
if len(seed_clean['Seed']) <= 16 and len(seed_clean['Seed']) >= 1:
    print("All seed values are valid (between 1 and 16).")