# NCAA Bracket Model — Feature Engineering

In [220]:
import pandas as pd
import numpy as np

In [221]:
pd.set_option('display.max_rows', 100)

In [222]:
def show_columns(df):
    for col in df.columns:
        print(col)

## Step 1: Team season averages

In [223]:
season_stats = pd.read_csv("../data/raw/MRegularSeasonDetailedResults.csv")
season_stats.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [224]:
show_columns(season_stats)

Season
DayNum
WTeamID
WScore
LTeamID
LScore
WLoc
NumOT
WFGM
WFGA
WFGM3
WFGA3
WFTM
WFTA
WOR
WDR
WAst
WTO
WStl
WBlk
WPF
LFGM
LFGA
LFGM3
LFGA3
LFTM
LFTA
LOR
LDR
LAst
LTO
LStl
LBlk
LPF

In [225]:
winners = season_stats[['Season', 'WTeamID', 'WScore', 'LScore', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'WOR']]
winners.rename(columns={'WTeamID': 'TeamID', 'WScore': 'Score', 'LScore': 'OppScore', 'WFGM': 'FGM', 'WFGA': 'FGA', 'WFGM3': 'FGM3', 'WFGA3': 'FGA3', 'WFTM': 'FTM', 'WFTA': 'FTA', 'WAst': 'Ast', 'WTO': 'TO', 'WStl': 'Stl', 'WBlk': 'Blk', 'WPF': 'PF', 'WOR': 'OR'}, inplace=True)
winners['Win'] = 1
winners.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,OR,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,14,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,15,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,17,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,6,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,17,1

In [226]:
losers = season_stats[['Season', 'LTeamID', 'LScore', 'WScore', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'LOR']]
losers.rename(columns={'LTeamID': 'TeamID', 'LScore': 'Score', 'WScore': 'OppScore', 'LFGM': 'FGM', 'LFGA': 'FGA', 'LFGM3': 'FGM3', 'LFGA3': 'FGA3', 'LFTM': 'FTM', 'LFTA': 'FTA', 'LAst': 'Ast', 'LTO': 'TO', 'LStl': 'Stl', 'LBlk': 'Blk', 'LPF': 'PF', 'LOR': 'OR'}, inplace=True)
losers['Win'] = 0
losers.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,OR,Win
0,2003,1328,62,68,22,53,2,10,16,22,8,18,9,2,20,10,0
1,2003,1393,63,70,24,67,6,24,9,20,7,12,8,6,16,20,0
2,2003,1437,61,73,22,73,3,26,14,23,9,12,2,5,23,31,0
3,2003,1457,50,56,18,49,6,22,8,15,9,19,4,3,23,17,0
4,2003,1208,71,77,24,62,6,16,17,27,12,10,7,1,14,21,0

In [227]:
team_stats = pd.concat([winners, losers], ignore_index=True)
team_stats.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,OR,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,14,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,15,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,17,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,6,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,17,1

In [228]:
# Verifying the proper amount of rows
print(f"Number of rows in winners: {len(winners)}\nNumber of rows in losers: {len(losers)}\nTotal rows in team_stats: {len(team_stats)}")
if len(winners) + len(losers) == len(team_stats) and len(season_stats) * 2 == len(team_stats):
    print("The number of rows in team_stats is correct.")

Number of rows in winners: 118882
Number of rows in losers: 118882
Total rows in team_stats: 237764
The number of rows in team_stats is correct.

In [229]:
season_averages = team_stats.groupby(['Season', 'TeamID']).mean().reset_index().sort_values(by=['Season', 'TeamID'])    
season_averages.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,OR,Win
0,2003,1102,57.250000,57.000000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,13.000000,11.428571,5.964286,1.785714,18.750000,4.178571,0.428571
1,2003,1103,78.777778,78.148148,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,15.222222,12.629630,7.259259,2.333333,19.851852,9.777778,0.481481
2,2003,1104,69.285714,65.000000,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,12.107143,13.285714,6.607143,3.785714,18.035714,13.571429,0.607143
3,2003,1105,71.769231,76.653846,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,14.538462,18.653846,9.307692,2.076923,20.230769,13.500000,0.269231
4,2003,1106,63.607143,63.750000,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,11.678571,17.035714,8.357143,3.142857,18.178571,12.285714,0.464286

In [230]:
season_averages.shape

(7981, 17)

In [231]:
checkwin = season_averages[(season_averages['Win'] < 0) | (season_averages['Win'] > 1)]
if len(checkwin) > 0:
    print("There are invalid values in the 'Win' column.")
else:
    print("All values in the 'Win' column are valid (0 or 1).")

All values in the 'Win' column are valid (0 or 1).

In [232]:
print(season_averages.shape)
season_averages

(7981, 17)

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,OR,Win
0,2003,1102,57.250000,57.000000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,13.000000,11.428571,5.964286,1.785714,18.750000,4.178571,0.428571
1,2003,1103,78.777778,78.148148,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,15.222222,12.629630,7.259259,2.333333,19.851852,9.777778,0.481481
2,2003,1104,69.285714,65.000000,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,12.107143,13.285714,6.607143,3.785714,18.035714,13.571429,0.607143
3,2003,1105,71.769231,76.653846,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,14.538462,18.653846,9.307692,2.076923,20.230769,13.500000,0.269231
4,2003,1106,63.607143,63.750000,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,11.678571,17.035714,8.357143,3.142857,18.178571,12.285714,0.464286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7976,2025,1476,67.333333,70.900000,23.300000,53.966667,8.500000,24.000000,12.233333,16.966667,14.066667,11.300000,5.966667,2.600000,16.733333,7.166667,0.433333
7977,2025,1477,64.354839,74.870968,23.000000,55.290323,8.387097,26.709677,9.967742,15.483871,14.161290,14.612903,8.387097,3.903226,16.774194,7.935484,0.161290
7978,2025,1478,71.933333,81.400000,24.800000,55.400000,7.500000,22.900000,14.833333,20.866667,13.466667,12.933333,6.666667,2.066667,19.300000,7.466667,0.233333
7979,2025,1479,65.785714,71.750000,22.678571,53.821429,7.000000,19.607143,13.428571,16.642857,13.107143,9.750000,6.607143,1.892857,16.678571,6.214286,0.428571
7980,2025,1480,67.766667,78.833333,25.333333,59.300000,5.300000,17.866667,11.800000,17.100000,12.966667,10.533333,6.866667,2.966667,15.833333,8.166667,0.166667

## Step 2: Seed Data

In [233]:
seeds = pd.read_csv("../data/raw/MNCAATourneySeeds.csv")
seeds.head()

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [234]:
seed_clean = seeds.copy()
seed_clean['Seed'] = seed_clean['Seed'].str.replace(r'[a-zA-Z]', '', regex=True).astype(int)
seed_clean = seed_clean[['Season', 'TeamID', 'Seed']]
seed_clean.head()

   Season  TeamID  Seed
0    1985    1207     1
1    1985    1210     2
2    1985    1228     3
3    1985    1260     4
4    1985    1374     5

In [235]:
if (seed_clean['Seed'] <= 16).all() and (seed_clean['Seed'] >= 1).all():
    print("All seed values are valid (between 1 and 16).")

All seed values are valid (between 1 and 16).

In [236]:
print(seed_clean.shape)
seed_clean

(2626, 3)

      Season  TeamID  Seed
0       1985    1207     1
1       1985    1210     2
2       1985    1228     3
3       1985    1260     4
4       1985    1374     5
...      ...     ...   ...
2621    2025    1161    12
2622    2025    1213    13
2623    2025    1423    14
2624    2025    1303    15
2625    2025    1313    16

[2626 rows x 3 columns]

## Step 3: Massey Rankings

In [237]:
massey = pd.read_csv("../data/raw/MMasseyOrdinals.csv")
massey.head()

   Season  RankingDayNum SystemName  TeamID  OrdinalRank
0    2003             35        SEL    1102          159
1    2003             35        SEL    1103          229
2    2003             35        SEL    1104           12
3    2003             35        SEL    1105          314
4    2003             35        SEL    1106          260

In [238]:
massey_clean = massey.copy()
massey_clean = massey_clean[(massey_clean['RankingDayNum'] == 133) & massey_clean['SystemName'].isin(['POM', 'SAG', 'MOR', 'DUN'])].reset_index(drop=True)
massey_clean = massey_clean[['Season', 'TeamID', 'SystemName', 'OrdinalRank']]
massey_clean.head()

   Season  TeamID SystemName  OrdinalRank
0    2003    1102        DUN           97
1    2003    1103        DUN          165
2    2003    1104        DUN           43
3    2003    1105        DUN          306
4    2003    1106        DUN          305

In [239]:
massey_pivot = massey_clean.pivot(index = ['Season', 'TeamID'], columns = 'SystemName', values = 'OrdinalRank').reset_index()
massey_pivot.columns.name = None
massey_pivot.head()

   Season  TeamID    DUN    MOR    POM    SAG
0    2003    1102   97.0  132.0  160.0  149.0
1    2003    1103  165.0  139.0  163.0  172.0
2    2003    1104   43.0   26.0   33.0   37.0
3    2003    1105  306.0  309.0  307.0  312.0
4    2003    1106  305.0  294.0  263.0  268.0

In [240]:
massey_pivot.isnull().sum()

Season       0
TeamID       0
DUN       1358
MOR          0
POM          3
SAG        726
dtype: int64

In [241]:
# Cleaning up massey data
# Note: DUN has no data for 2004, 2005, 2015, 2018. SAG has no data for 2024, 2025.
# For these seasons all teams receive the same forward-filled median value,
# meaning these features carry no discriminating power for those years.
massey_pivot['DUN'] = massey_pivot.groupby('Season')['DUN'].transform(lambda x: x.fillna(x.median())) 
massey_pivot['MOR'] = massey_pivot.groupby('Season')['MOR'].transform(lambda x: x.fillna(x.median()))
massey_pivot['POM'] = massey_pivot.groupby('Season')['POM'].transform(lambda x: x.fillna(x.median()))
massey_pivot['SAG'] = massey_pivot.groupby('Season')['SAG'].transform(lambda x: x.fillna(x.median()))
massey_pivot.head()

   Season  TeamID    DUN    MOR    POM    SAG
0    2003    1102   97.0  132.0  160.0  149.0
1    2003    1103  165.0  139.0  163.0  172.0
2    2003    1104   43.0   26.0   33.0   37.0
3    2003    1105  306.0  309.0  307.0  312.0
4    2003    1106  305.0  294.0  263.0  268.0

In [242]:
massey_pivot.isnull().sum()

Season       0
TeamID       0
DUN       1358
MOR          0
POM          0
SAG        726
dtype: int64

In [243]:
massey_pivot.groupby('Season')['DUN'].count()

Season
2003    327
2004      0
2005      0
2006    334
2007    336
2008    341
2009    347
2010    347
2011    345
2012    345
2013    347
2014    351
2015      0
2016    351
2017    351
2018      0
2019    353
2021    347
2022    358
2023    363
2024    362
2025    364
Name: DUN, dtype: int64

In [244]:
massey_pivot.groupby('Season')['SAG'].count()

Season
2003    327
2004    326
2005    330
2006    334
2007    336
2008    341
2009    347
2010    347
2011    345
2012    345
2013    347
2014    351
2015    351
2016    351
2017    351
2018    351
2019    353
2021    347
2022    358
2023    363
2024      0
2025      0
Name: SAG, dtype: int64

In [245]:
#Handeling Missing Values in DUN
dun_median = massey_pivot.groupby('Season')['DUN'].median().sort_index().ffill()
print(dun_median)
season_medians = massey_pivot['Season'].map(dun_median)
massey_pivot['DUN'] = massey_pivot['DUN'].fillna(season_medians)
massey_pivot.isnull().sum()

Season
2003    164.0
2004    164.0
2005    164.0
2006    167.5
2007    168.5
2008    171.0
2009    174.0
2010    174.0
2011    173.0
2012    173.0
2013    174.0
2014    176.0
2015    176.0
2016    176.0
2017    176.0
2018    176.0
2019    177.0
2021    174.0
2022    179.5
2023    182.0
2024    181.5
2025    182.5
Name: DUN, dtype: float64

Season      0
TeamID      0
DUN         0
MOR         0
POM         0
SAG       726
dtype: int64

In [246]:
#Handeling Missing Values in SAG
sag_median = massey_pivot.groupby('Season')['SAG'].median().sort_index().ffill()
print(sag_median)
season_medians = massey_pivot['Season'].map(sag_median)
massey_pivot['SAG'] = massey_pivot['SAG'].fillna(season_medians)
massey_pivot.isnull().sum()

Season
2003    164.0
2004    163.5
2005    165.5
2006    167.5
2007    168.5
2008    171.0
2009    174.0
2010    174.0
2011    173.0
2012    173.0
2013    174.0
2014    176.0
2015    176.0
2016    176.0
2017    176.0
2018    176.0
2019    177.0
2021    174.0
2022    179.5
2023    182.0
2024    182.0
2025    182.0
Name: SAG, dtype: float64

Season    0
TeamID    0
DUN       0
MOR       0
POM       0
SAG       0
dtype: int64

In [247]:
print(massey_pivot.shape)
massey_pivot

(7627, 6)

      Season  TeamID    DUN    MOR    POM    SAG
0       2003    1102   97.0  132.0  160.0  149.0
1       2003    1103  165.0  139.0  163.0  172.0
2       2003    1104   43.0   26.0   33.0   37.0
3       2003    1105  306.0  309.0  307.0  312.0
4       2003    1106  305.0  294.0  263.0  268.0
...      ...     ...    ...    ...    ...    ...
7622    2025    1476  299.0  328.0  322.0  182.0
7623    2025    1477  353.0  298.0  330.0  182.0
7624    2025    1478  339.0  344.0  354.0  182.0
7625    2025    1479  290.0  312.0  342.0  182.0
7626    2025    1480  346.0  352.0  349.0  182.0

[7627 rows x 6 columns]

## Step 4: Tournament History

##### Seed Features

In [248]:
tourney_results = pd.read_csv("../data/raw/MNCAATourneyCompactResults.csv")
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [249]:
bracket_winners = tourney_results[['Season', 'WTeamID', 'DayNum']]
bracket_winners.rename(columns={'WTeamID': 'TeamID'}, inplace=True)

bracket_losers = tourney_results[['Season', 'LTeamID', 'DayNum']]
bracket_losers.rename(columns={'LTeamID': 'TeamID'}, inplace=True)

In [250]:
tourney_appearances = pd.concat([bracket_winners, bracket_losers], ignore_index=True)
tourney_appearances.head()

   Season  TeamID  DayNum
0    1985    1116     136
1    1985    1120     136
2    1985    1207     136
3    1985    1229     136
4    1985    1242     136

In [251]:
deepest_game = tourney_appearances.groupby(['Season', 'TeamID'])['DayNum'].max().reset_index()
deepest_game

      Season  TeamID  DayNum
0       1985    1104     144
1       1985    1112     137
2       1985    1116     138
3       1985    1120     144
4       1985    1130     143
...      ...     ...     ...
2552    2024    1443     137
2553    2024    1447     136
2554    2024    1450     138
2555    2024    1458     137
2556    2024    1463     139

[2557 rows x 3 columns]

In [252]:
conditions = [
    deepest_game['DayNum'] == 154,
    deepest_game['DayNum'] == 152,
    (deepest_game['DayNum'] >= 145) & (deepest_game['DayNum'] < 152),
    (deepest_game['DayNum'] >= 143) & (deepest_game['DayNum'] < 145),
    (deepest_game['DayNum'] >= 138) & (deepest_game['DayNum'] < 143),
    (deepest_game['DayNum'] > 135) & (deepest_game['DayNum'] < 138),
    (deepest_game['DayNum'] == 135) |(deepest_game['DayNum'] == 134),
    deepest_game['DayNum'] < 134
]

values = [6, 5, 4, 3, 2, 1, 0.5, 0]

deepest_game['Round'] = np.select(conditions, values, default=0)
deepest_game

      Season  TeamID  DayNum  Round
0       1985    1104     144    3.0
1       1985    1112     137    1.0
2       1985    1116     138    2.0
3       1985    1120     144    3.0
4       1985    1130     143    3.0
...      ...     ...     ...    ...
2552    2024    1443     137    1.0
2553    2024    1447     136    1.0
2554    2024    1450     138    2.0
2555    2024    1458     137    1.0
2556    2024    1463     139    2.0

[2557 rows x 4 columns]

In [253]:
# Verifying the distribution of rounds
print(deepest_game['Round'].value_counts())
print(deepest_game['Round'].max())

Round
1.0    1236
2.0     639
3.0     304
4.0     164
6.0      78
5.0      78
0.5      58
Name: count, dtype: int64
6.0

In [254]:
all_teams = deepest_game['TeamID'].unique()
all_seasons = deepest_game['Season'].unique()
possible_indices = pd.MultiIndex.from_product([all_seasons, all_teams], names=['Season', 'TeamID'])
possible_indices = possible_indices.to_frame(index=False)

In [255]:
tournament_history = pd.merge(possible_indices, deepest_game, on=['Season', 'TeamID'], how='left')
tournament_history = tournament_history.fillna({'Round': 0})
tournament_history.head()

   Season  TeamID  DayNum  Round
0    1985    1104   144.0    3.0
1    1985    1112   137.0    1.0
2    1985    1116   138.0    2.0
3    1985    1120   144.0    3.0
4    1985    1130   143.0    3.0

In [256]:
teams = pd.read_csv("../data/raw/Mteams.csv")
teams.head()

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2025
1    1102    Air Force           1985          2025
2    1103        Akron           1985          2025
3    1104      Alabama           1985          2025
4    1105  Alabama A&M           2000          2025

In [257]:
tournament_history = pd.merge(tournament_history, teams[['TeamID', 'FirstD1Season']], on='TeamID', how='left')
tournament_history.shape

(12051, 5)

In [258]:
tournament_history = tournament_history[tournament_history['Season'] >= tournament_history['FirstD1Season']]
tournament_history.drop(columns=['FirstD1Season'], inplace=True)
tournament_history.shape

(11367, 4)

In [259]:
tournament_history['round_last_year'] = tournament_history.groupby('TeamID')['Round'].shift(1)
tournament_history['round_avg_3yr'] = tournament_history.groupby('TeamID')['Round'].transform(lambda x: x.shift(1).rolling(window = 3, min_periods = 1).mean())
tournament_history['appearances_5yr'] = tournament_history.groupby('TeamID')['Round'].transform(lambda x: x.shift(1).rolling(window = 5, min_periods = 1).apply(lambda x: (x > 0).sum()))  
# min_periods=1 means early seasons use a window shorter than 5 years.
# appearances_5yr reflects available history only, not always a full 5-year count. 
tournament_history

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
0,1985,1104,144.0,3.0,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0

In [260]:
# Verifying the new features for a specific team (Duke my school & the best school OAT :))
tournament_history[tournament_history['TeamID'] == 1181]

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
7,1985,1181,139.0,2.0,NaN,NaN,NaN
316,1986,1181,154.0,6.0,2.0,2.000000,1.0
625,1987,1181,144.0,3.0,6.0,4.000000,2.0
934,1988,1181,152.0,5.0,3.0,3.666667,3.0
1243,1989,1181,152.0,5.0,5.0,4.666667,4.0
1552,1990,1181,154.0,6.0,5.0,4.333333,5.0
1861,1991,1181,154.0,6.0,6.0,5.333333,5.0
2170,1992,1181,154.0,6.0,6.0,5.666667,5.0
2479,1993,1181,138.0,2.0,6.0,6.000000,5.0
2788,1994,1181,154.0,6.0,2.0,4.666667,5.0
3097,1995,1181,NaN,0.0,6.0,4.666667,5.0
3406,1996,1181,136.0,1.0,0.0,2.666667,4.0
3715,1997,1181,139.0,2.0,1.0,2.333333,4.0
4024,1998,1181,146.0,4.0,2.0,1.000000,4.0
4333,1999,1181,154.0,6.0,4.0,2.333333,4.0
4642,2000,1181,144.0,3.0,6.0,4.000000,4.0
4951,2001,1181,154.0,6.0,3.0,4.333333,5.0
5260,2002,1181,143.0,3.0,6.0,5.000000,5.0
5569,2003,1181,143.0,3.0,3.0,4.000000,5.0
5878,2004,1181,152.0,5.0,3.0,4.000000,5.0
6187,2005,1181,144.0,3.0,5.0,3.666667,5.0
6496,2006,1181,143.0,3.0,3.0,3.666667,5.0
6805,2007,1181,136.0,1.0,3.0,3.666667,5.0
7114,2008,1181,138.0,2.0,1.0,2.333333,5.0
7423,2009,1181,143.0,3.0,2.0,2.000000,5.0
7732,2010,1181,154.0,6.0,3.0,2.000000,5.0
8041,2011,1181,143.0,3.0,6.0,3.666667,5.0
8350,2012,1181,137.0,1.0,3.0,4.000000,5.0
8659,2013,1181,146.0,4.0,1.0,3.333333,5.0
8968,2014,1181,137.0,1.0,4.0,2.666667,5.0
9277,2015,1181,154.0,6.0,1.0,2.000000,5.0
9586,2016,1181,143.0,3.0,6.0,3.666667,5.0
9895,2017,1181,139.0,2.0,3.0,3.333333,5.0
10204,2018,1181,146.0,4.0,2.0,3.666667,5.0
10513,2019,1181,146.0,4.0,4.0,3.000000,5.0
10822,2021,1181,NaN,0.0,4.0,3.333333,5.0
11131,2022,1181,152.0,5.0,0.0,2.666667,4.0
11440,2023,1181,138.0,2.0,5.0,3.000000,4.0
11749,2024,1181,146.0,4.0,2.0,2.333333,4.0

In [261]:
print(tournament_history.shape)
tournament_history

(11367, 7)

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
0,1985,1104,144.0,3.0,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0

##### Winner Each Year Feature

In [262]:
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [263]:
champions = tourney_results[['Season', 'WTeamID', 'DayNum']][tourney_results['DayNum'] == 154]
champions.rename(columns={'WTeamID': 'TeamID'}, inplace=True)
champions['won_championship_last_year'] = 1
champions['Season'] += 1
champions.loc[champions['Season'] == 2020, 'Season'] = 2021 # Adjusting for the 2020 season where there was no champion due to the pandemic
champions.head()

     Season  TeamID  DayNum  won_championship_last_year
62     1986    1437     154                           1
125    1987    1257     154                           1
188    1988    1231     154                           1
251    1989    1242     154                           1
314    1990    1276     154                           1

In [264]:
champions[champions['TeamID'] == 1438]

      Season  TeamID  DayNum  won_championship_last_year
2250    2021    1438     154                           1

In [265]:
champions.drop(columns=['DayNum'], inplace=True)
tournament_history = pd.merge(tournament_history, champions, on=['Season', 'TeamID'], how='left')
tournament_history = tournament_history.fillna({'won_championship_last_year': 0})
tournament_history
tournament_history.shape

(11367, 8)

In [266]:
# Verifying the new feature for a specific team (again Duke :) )
tournament_history[tournament_history['Season'].isin([1991,1992,1993]) & (tournament_history['TeamID'] == 1181)]

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year
1586,1991,1181,154.0,6.0,6.0,5.333333,5.0,0.0
1857,1992,1181,154.0,6.0,6.0,5.666667,5.0,1.0
2132,1993,1181,138.0,2.0,6.0,6.000000,5.0,1.0

In [267]:
print(tournament_history.shape)
tournament_history

(11367, 8)

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year
0,1985,1104,144.0,3.0,NaN,NaN,NaN,0.0
1,1985,1112,137.0,1.0,NaN,NaN,NaN,0.0
2,1985,1116,138.0,2.0,NaN,NaN,NaN,0.0
3,1985,1120,144.0,3.0,NaN,NaN,NaN,0.0
4,1985,1130,143.0,3.0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...
11362,2024,1202,NaN,0.0,2.0,0.666667,1.0,0.0
11363,2024,1244,NaN,0.0,1.0,0.333333,1.0,0.0
11364,2024,1182,138.0,2.0,0.0,0.000000,0.0,0.0
11365,2024,1212,137.0,1.0,0.0,0.000000,0.0,0.0
11366,2024,1391,137.0,1.0,0.0,0.000000,0.0,0.0

## Step 5: Strength of Schedule

In [268]:
sos_winners = season_stats[['Season', 'WTeamID', 'LTeamID']]
sos_winners.rename(columns={'WTeamID': 'TeamID', 'LTeamID': 'OpponentID'}, inplace=True)

sos_losers = season_stats[['Season', 'LTeamID', 'WTeamID']]
sos_losers.rename(columns={'LTeamID': 'TeamID', 'WTeamID': 'OpponentID'}, inplace=True)

In [269]:
sos_winners.head()

   Season  TeamID  OpponentID
0    2003    1104        1328
1    2003    1272        1393
2    2003    1266        1437
3    2003    1296        1457
4    2003    1400        1208

In [270]:
sos_losers.head()

   Season  TeamID  OpponentID
0    2003    1328        1104
1    2003    1393        1272
2    2003    1437        1266
3    2003    1457        1296
4    2003    1208        1400

In [271]:
sos_matchups = pd.concat([sos_winners, sos_losers], ignore_index=True)
sos_matchups.head()

   Season  TeamID  OpponentID
0    2003    1104        1328
1    2003    1272        1393
2    2003    1266        1437
3    2003    1296        1457
4    2003    1400        1208

In [272]:
sos_with_winrate = pd.merge(sos_matchups, season_averages[['Season', 'TeamID', 'Win']], left_on=['Season', 'OpponentID'], right_on=['Season', 'TeamID'], how='left')
sos_with_winrate.drop(columns=['TeamID_y'], inplace=True)
sos_with_winrate.rename(columns={'TeamID_x': 'TeamID', 'Win': 'OpponentWinRate'}, inplace=True)
sos_with_winrate.head()

   Season  TeamID  OpponentID  OpponentWinRate
0    2003    1104        1328         0.800000
1    2003    1272        1393         0.827586
2    2003    1266        1437         0.500000
3    2003    1296        1457         0.642857
4    2003    1400        1208         0.703704

In [273]:
sos = sos_with_winrate.groupby(['Season', 'TeamID'])['OpponentWinRate'].mean().reset_index()
sos.head()

   Season  TeamID  OpponentWinRate
0    2003    1102         0.530644
1    2003    1103         0.489779
2    2003    1104         0.572492
3    2003    1105         0.415228
4    2003    1106         0.458062

## Step 6: Efficiency Ratings

In [274]:
season_averages['Possessions'] = season_averages['FGA'] - season_averages['OR'] + 0.44 * season_averages['FTA'] + season_averages['TO']
season_averages['OffensiveEfficiency'] = season_averages['Score'] / season_averages['Possessions'] * 100
# Note: DefensiveEfficiency uses the team's own possession estimate as the denominator.
# The correct approach would use the opponent's possession count, but that data
# is not available in this DataFrame. The approximation is small since teams
# playing each other tend to have similar possession counts.
season_averages['DefensiveEfficiency'] = season_averages['OppScore'] / season_averages['Possessions'] * 100
season_averages['EfficiencyMargin'] = season_averages['OffensiveEfficiency'] - season_averages['DefensiveEfficiency']
season_averages[['Season', 'TeamID', 'Possessions', 'OffensiveEfficiency', 'DefensiveEfficiency', 'EfficiencyMargin']].head()

,Season,TeamID,Possessions,OffensiveEfficiency,DefensiveEfficiency,EfficiencyMargin
0,2003,1102,54.562857,104.924857,104.466670,0.458187
1,2003,1103,70.078519,112.413589,111.515126,0.898463
2,2003,1104,66.101429,104.817272,98.333730,6.483543
3,2003,1105,76.381538,93.961489,100.356510,-6.395021
4,2003,1106,67.280000,94.540938,94.753270,-0.212332

## Step 7: Merging All Features

In [275]:
#tournament_history = pd.merge(tournament_history, champions, on=['Season', 'TeamID'], how='left')
#tournament_history = tournament_history.fillna({'won_championship_last_year': 0})

team_features = pd.merge(tournament_history, season_averages, on=['Season', 'TeamID'], how='left')
team_features = pd.merge(team_features, seed_clean, on=['Season', 'TeamID'], how='left')
team_features = pd.merge(team_features, massey_pivot, on=['Season', 'TeamID'], how='left')
team_features = pd.merge(team_features, sos, on=['Season', 'TeamID'], how='left')
team_features = team_features.drop(columns=['Win'])

print(team_features.shape)
team_features.isnull().sum()

(11367, 32)

Season                           0
TeamID                           0
DayNum                        8810
Round                            0
round_last_year                309
round_avg_3yr                  309
appearances_5yr                309
won_championship_last_year       0
Score                         4964
OppScore                      4964
FGM                           4964
FGA                           4964
FGM3                          4964
FGA3                          4964
FTM                           4964
FTA                           4964
Ast                           4964
TO                            4964
Stl                           4964
Blk                           4964
PF                            4964
OR                            4964
Possessions                   4964
OffensiveEfficiency           4964
DefensiveEfficiency           4964
EfficiencyMargin              4964
Seed                          8809
DUN                           4964
MOR                           4964
POM                           4964
SAG                           4964
OpponentWinRate               4964
dtype: int64

In [276]:
show_columns(team_features)

Season
TeamID
DayNum
Round
round_last_year
round_avg_3yr
appearances_5yr
won_championship_last_year
Score
OppScore
FGM
FGA
FGM3
FGA3
FTM
FTA
Ast
TO
Stl
Blk
PF
OR
Possessions
OffensiveEfficiency
DefensiveEfficiency
EfficiencyMargin
Seed
DUN
MOR
POM
SAG
OpponentWinRate

## Step 8: Matchup Table

In [277]:
tourney_results = pd.read_csv("../data/raw/MNCAATourneyCompactResults.csv")
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [278]:
matchups = tourney_results.copy()
np.random.seed(1) # Setting a seed for reproducibility
matchups['random_team'] = np.random.choice([True, False], size = len(matchups))
matchups.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT  random_team
0    1985     136     1116      63     1234      54    N      0        False
1    1985     136     1120      59     1345      58    N      0        False
2    1985     136     1207      68     1250      43    N      0         True
3    1985     136     1229      58     1425      55    N      0         True
4    1985     136     1242      49     1325      38    N      0        False

In [279]:
matchups['TeamA_Id'] = np.where(matchups['random_team'], matchups['WTeamID'], matchups['LTeamID'])
matchups['TeamB_Id'] = np.where(matchups['random_team'], matchups['LTeamID'], matchups['WTeamID'])
matchups['Results'] = np.where(matchups['random_team'], 1, 0)
# Cleaning up the matchups data
matchups_cleaned = matchups[['Season', 'DayNum', 'TeamA_Id', 'TeamB_Id', 'Results']]
matchups_cleaned.head()

   Season  DayNum  TeamA_Id  TeamB_Id  Results
0    1985     136      1234      1116        0
1    1985     136      1345      1120        0
2    1985     136      1207      1250        1
3    1985     136      1229      1425        1
4    1985     136      1325      1242        0

In [280]:
team_features.head()

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,OppScore,...,Possessions,OffensiveEfficiency,DefensiveEfficiency,EfficiencyMargin,Seed,DUN,MOR,POM,SAG,OpponentWinRate
0,1985,1104,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN

In [281]:
final_features = pd.merge(matchups_cleaned, team_features, left_on = ['Season', 'TeamA_Id'], right_on = ['Season', 'TeamID'], suffixes = ('', '_A'), how='left')
final_features = pd.merge(final_features, team_features, left_on = ['Season', 'TeamB_Id'], right_on = ['Season', 'TeamID'], suffixes = ('', '_B'), how='left')
final_features.head()

,Season,DayNum,TeamA_Id,TeamB_Id,Results,TeamID,DayNum_A,Round,round_last_year,round_avg_3yr,...,Possessions_B,OffensiveEfficiency_B,DefensiveEfficiency_B,EfficiencyMargin_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B,OpponentWinRate_B
0,1985,136,1234,1116,0,1234,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,1345,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,1207,154.0,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,1229,138.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,1325,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN

In [282]:
show_columns(final_features)

Season
DayNum
TeamA_Id
TeamB_Id
Results
TeamID
DayNum_A
Round
round_last_year
round_avg_3yr
appearances_5yr
won_championship_last_year
Score
OppScore
FGM
FGA
FGM3
FGA3
FTM
FTA
Ast
TO
Stl
Blk
PF
OR
Possessions
OffensiveEfficiency
DefensiveEfficiency
EfficiencyMargin
Seed
DUN
MOR
POM
SAG
OpponentWinRate
TeamID_B
DayNum_B
Round_B
round_last_year_B
round_avg_3yr_B
appearances_5yr_B
won_championship_last_year_B
Score_B
OppScore_B
FGM_B
FGA_B
FGM3_B
FGA3_B
FTM_B
FTA_B
Ast_B
TO_B
Stl_B
Blk_B
PF_B
OR_B
Possessions_B
OffensiveEfficiency_B
DefensiveEfficiency_B
EfficiencyMargin_B
Seed_B
DUN_B
MOR_B
POM_B
SAG_B
OpponentWinRate_B

In [283]:
# Cleaning up final_features
final_features = final_features.drop(columns=['TeamID', 'TeamID_B', 'DayNum_A', 'DayNum_B', 'Round', 'Round_B'], errors='ignore')
final_features.head()

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,Possessions_B,OffensiveEfficiency_B,DefensiveEfficiency_B,EfficiencyMargin_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B,OpponentWinRate_B
0,1985,136,1234,1116,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN

In [284]:
show_columns(final_features)

Season
DayNum
TeamA_Id
TeamB_Id
Results
round_last_year
round_avg_3yr
appearances_5yr
won_championship_last_year
Score
OppScore
FGM
FGA
FGM3
FGA3
FTM
FTA
Ast
TO
Stl
Blk
PF
OR
Possessions
OffensiveEfficiency
DefensiveEfficiency
EfficiencyMargin
Seed
DUN
MOR
POM
SAG
OpponentWinRate
round_last_year_B
round_avg_3yr_B
appearances_5yr_B
won_championship_last_year_B
Score_B
OppScore_B
FGM_B
FGA_B
FGM3_B
FGA3_B
FTM_B
FTA_B
Ast_B
TO_B
Stl_B
Blk_B
PF_B
OR_B
Possessions_B
OffensiveEfficiency_B
DefensiveEfficiency_B
EfficiencyMargin_B
Seed_B
DUN_B
MOR_B
POM_B
SAG_B
OpponentWinRate_B

In [285]:
final_features['Season'].value_counts().sort_index()

Season
1985    63
1986    63
1987    63
1988    63
1989    63
1990    63
1991    63
1992    63
1993    63
1994    63
1995    63
1996    63
1997    63
1998    63
1999    63
2000    63
2001    64
2002    64
2003    64
2004    64
2005    64
2006    64
2007    64
2008    64
2009    64
2010    64
2011    67
2012    67
2013    67
2014    67
2015    67
2016    67
2017    67
2018    67
2019    67
2021    66
2022    67
2023    67
2024    67
Name: count, dtype: int64

### Final Features

In [286]:
final_features

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,Possessions_B,OffensiveEfficiency_B,DefensiveEfficiency_B,EfficiencyMargin_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B,OpponentWinRate_B
0,1985,136,1234,1116,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,2024,146,1301,1181,1,1.0,0.333333,2.0,0.0,76.361111,...,68.393750,116.741296,98.601846,18.139450,4.0,10.0,11.0,8.0,182.0,0.528190
2514,2024,146,1397,1345,0,3.0,2.000000,5.0,0.0,79.468750,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359
2515,2024,152,1163,1104,1,6.0,3.000000,3.0,1.0,81.470588,...,75.568750,120.089323,107.269870,12.819452,4.0,14.0,14.0,13.0,182.0,0.626118
2516,2024,152,1301,1345,0,1.0,0.333333,2.0,0.0,76.361111,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359
2517,2024,154,1163,1345,1,6.0,3.000000,3.0,1.0,81.470588,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359

## Step 9: Train/Validation/Test Split

In [287]:
print('Results' in final_features.columns)
print(final_features['Season'].min(), final_features['Season'].max())

True
1985 2024

In [288]:
# Getting proper date range
final_features = final_features[(final_features['Season'] >= 2003) & (final_features['Season'] <= 2024)].reset_index(drop=True)
final_features

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,Possessions_B,OffensiveEfficiency_B,DefensiveEfficiency_B,EfficiencyMargin_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B,OpponentWinRate_B
0,2003,134,1411,1421,0,0.0,0.000000,0.0,0.0,72.800000,...,69.933793,101.820441,112.175062,-10.354621,16.0,241.0,277.0,273.0,251.0,0.511096
1,2003,136,1436,1112,0,0.0,0.000000,0.0,0.0,67.793103,...,76.321429,111.651848,92.044923,19.606926,1.0,9.0,4.0,3.0,2.0,0.551868
2,2003,136,1113,1272,1,0.0,0.000000,0.0,0.0,75.965517,...,69.798621,106.760335,94.310726,12.449609,7.0,19.0,23.0,20.0,24.0,0.516632
3,2003,136,1141,1166,1,0.0,0.000000,0.0,0.0,79.344828,...,68.752727,115.257136,93.572046,21.685090,6.0,27.0,33.0,27.0,18.0,0.492723
4,2003,136,1143,1301,1,2.0,1.000000,2.0,0.0,74.482759,...,66.805333,108.374581,101.788280,6.586300,9.0,23.0,31.0,48.0,46.0,0.554099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,2024,146,1301,1181,1,1.0,0.333333,2.0,0.0,76.361111,...,68.393750,116.741296,98.601846,18.139450,4.0,10.0,11.0,8.0,182.0,0.528190
1378,2024,146,1397,1345,0,3.0,2.000000,5.0,0.0,79.468750,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359
1379,2024,152,1163,1104,1,6.0,3.000000,3.0,1.0,81.470588,...,75.568750,120.089323,107.269870,12.819452,4.0,14.0,14.0,13.0,182.0,0.626118
1380,2024,152,1301,1345,0,1.0,0.333333,2.0,0.0,76.361111,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359
1381,2024,154,1163,1345,1,6.0,3.000000,3.0,1.0,81.470588,...,69.333333,120.279720,101.180070,19.099650,1.0,3.0,6.0,3.0,182.0,0.593359

In [289]:
# Separating and Defining the features and target variable
X = final_features.drop(columns=['Results', 'TeamA_Id', 'TeamB_Id', 'DayNum'])
y = final_features[['Season', 'Results']]

In [290]:
#Creating train, validation, and test sets
X_train = X[X['Season'] <= 2022].drop(columns=['Season'])
y_train = y[y['Season'] <= 2022].drop(columns=['Season'])

X_val = X[X['Season'] == 2023].drop(columns=['Season'])
y_val = y[y['Season'] == 2023].drop(columns=['Season']) 

X_test = X[X['Season'] == 2024].drop(columns=['Season'])
y_test = y[y['Season'] == 2024].drop(columns=['Season'])    

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((1248, 56), (1248, 1), (67, 56), (67, 1), (67, 56), (67, 1))

In [291]:
# Saving dataset to parquet files
X_train.to_parquet("../data/processed/X_train.parquet", engine='fastparquet')
X_val.to_parquet("../data/processed/X_val.parquet", engine='fastparquet')
X_test.to_parquet("../data/processed/X_test.parquet", engine='fastparquet')

y_train.to_parquet("../data/processed/y_train.parquet", engine='fastparquet')
y_val.to_parquet("../data/processed/y_val.parquet", engine='fastparquet')
y_test.to_parquet("../data/processed/y_test.parquet", engine='fastparquet')

print("Splits saved.")

Splits saved.

In [292]:
# Saving the final features dataset for future reference in evaluating results
# Note: final_features.parquet retains DayNum for interpretability purposes (used in results analysis).
# DayNum is dropped when creating X before modeling to prevent round information from leaking into features.
final_features.to_parquet("../data/processed/final_features.parquet", engine='fastparquet')