# NCAA Bracket Model — Feature Engineering

In [601]:
import pandas as pd
import numpy as np

In [602]:
def show_columns(df):
    for col in df.columns:
        print(col)

## Step 1: Build Team Season Averages

In [603]:
season_stats = pd.read_csv("../data/raw/MRegularSeasonDetailedResults.csv")
season_stats.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [604]:
show_columns(season_stats)

Season
DayNum
WTeamID
WScore
LTeamID
LScore
WLoc
NumOT
WFGM
WFGA
WFGM3
WFGA3
WFTM
WFTA
WOR
WDR
WAst
WTO
WStl
WBlk
WPF
LFGM
LFGA
LFGM3
LFGA3
LFTM
LFTA
LOR
LDR
LAst
LTO
LStl
LBlk
LPF

In [605]:
winners = season_stats[['Season', 'WTeamID', 'WScore', 'LScore', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF']]
winners.rename(columns={'WTeamID': 'TeamID', 'WScore': 'Score', 'LScore': 'OppScore', 'WFGM': 'FGM', 'WFGA': 'FGA', 'WFGM3': 'FGM3', 'WFGA3': 'FGA3', 'WFTM': 'FTM', 'WFTA': 'FTA', 'WAst': 'Ast', 'WTO': 'TO', 'WStl': 'Stl', 'WBlk': 'Blk', 'WPF': 'PF'}, inplace=True)
winners['Win'] = 1
winners.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,1

In [606]:
losers = season_stats[['Season', 'LTeamID', 'LScore', 'WScore', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']]
losers.rename(columns={'LTeamID': 'TeamID', 'LScore': 'Score', 'WScore': 'OppScore', 'LFGM': 'FGM', 'LFGA': 'FGA', 'LFGM3': 'FGM3', 'LFGA3': 'FGA3', 'LFTM': 'FTM', 'LFTA': 'FTA', 'LAst': 'Ast', 'LTO': 'TO', 'LStl': 'Stl', 'LBlk': 'Blk', 'LPF': 'PF'}, inplace=True)
losers['Win'] = 0
losers.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1328,62,68,22,53,2,10,16,22,8,18,9,2,20,0
1,2003,1393,63,70,24,67,6,24,9,20,7,12,8,6,16,0
2,2003,1437,61,73,22,73,3,26,14,23,9,12,2,5,23,0
3,2003,1457,50,56,18,49,6,22,8,15,9,19,4,3,23,0
4,2003,1208,71,77,24,62,6,16,17,27,12,10,7,1,14,0

In [607]:
team_stats = pd.concat([winners, losers], ignore_index=True)
team_stats.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1104,68,62,27,58,3,14,11,18,13,23,7,1,22,1
1,2003,1272,70,63,26,62,8,20,10,19,16,13,4,4,18,1
2,2003,1266,73,61,24,58,8,18,17,29,15,10,5,2,25,1
3,2003,1296,56,50,18,38,3,9,17,31,11,12,14,2,18,1
4,2003,1400,77,71,30,61,6,14,11,13,12,14,4,4,20,1

In [608]:
# Verifying the proper amount of rows
print(f"Number of rows in winners: {len(winners)}\nNumber of rows in losers: {len(losers)}\nTotal rows in team_stats: {len(team_stats)}")
if len(winners) + len(losers) == len(team_stats) and len(season_stats) * 2 == len(team_stats):
    print("The number of rows in team_stats is correct.")

Number of rows in winners: 118882
Number of rows in losers: 118882
Total rows in team_stats: 237764
The number of rows in team_stats is correct.

In [609]:
season_averages = team_stats.groupby(['Season', 'TeamID']).mean().reset_index().sort_values(by=['Season', 'TeamID'])    
season_averages.head()

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1102,57.250000,57.000000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,13.000000,11.428571,5.964286,1.785714,18.750000,0.428571
1,2003,1103,78.777778,78.148148,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,15.222222,12.629630,7.259259,2.333333,19.851852,0.481481
2,2003,1104,69.285714,65.000000,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,12.107143,13.285714,6.607143,3.785714,18.035714,0.607143
3,2003,1105,71.769231,76.653846,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,14.538462,18.653846,9.307692,2.076923,20.230769,0.269231
4,2003,1106,63.607143,63.750000,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,11.678571,17.035714,8.357143,3.142857,18.178571,0.464286

In [610]:
season_averages.shape

(7981, 16)

In [611]:
checkwin = season_averages[(season_averages['Win'] < 0) | (season_averages['Win'] > 1)]
if len(checkwin) > 0:
    print("There are invalid values in the 'Win' column.")
else:
    print("All values in the 'Win' column are valid (0 or 1).")

All values in the 'Win' column are valid (0 or 1).

In [612]:
print(season_averages.shape)
season_averages

(7981, 16)

,Season,TeamID,Score,OppScore,FGM,FGA,FGM3,FGA3,FTM,FTA,Ast,TO,Stl,Blk,PF,Win
0,2003,1102,57.250000,57.000000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,13.000000,11.428571,5.964286,1.785714,18.750000,0.428571
1,2003,1103,78.777778,78.148148,27.148148,55.851852,5.444444,16.074074,19.037037,25.851852,15.222222,12.629630,7.259259,2.333333,19.851852,0.481481
2,2003,1104,69.285714,65.000000,24.035714,57.178571,6.357143,19.857143,14.857143,20.928571,12.107143,13.285714,6.607143,3.785714,18.035714,0.607143
3,2003,1105,71.769231,76.653846,24.384615,61.615385,7.576923,20.769231,15.423077,21.846154,14.538462,18.653846,9.307692,2.076923,20.230769,0.269231
4,2003,1106,63.607143,63.750000,23.428571,55.285714,6.107143,17.642857,10.642857,16.464286,11.678571,17.035714,8.357143,3.142857,18.178571,0.464286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7976,2025,1476,67.333333,70.900000,23.300000,53.966667,8.500000,24.000000,12.233333,16.966667,14.066667,11.300000,5.966667,2.600000,16.733333,0.433333
7977,2025,1477,64.354839,74.870968,23.000000,55.290323,8.387097,26.709677,9.967742,15.483871,14.161290,14.612903,8.387097,3.903226,16.774194,0.161290
7978,2025,1478,71.933333,81.400000,24.800000,55.400000,7.500000,22.900000,14.833333,20.866667,13.466667,12.933333,6.666667,2.066667,19.300000,0.233333
7979,2025,1479,65.785714,71.750000,22.678571,53.821429,7.000000,19.607143,13.428571,16.642857,13.107143,9.750000,6.607143,1.892857,16.678571,0.428571
7980,2025,1480,67.766667,78.833333,25.333333,59.300000,5.300000,17.866667,11.800000,17.100000,12.966667,10.533333,6.866667,2.966667,15.833333,0.166667

## Step 2: Clean and Build Seed Data

In [613]:
seeds = pd.read_csv("../data/raw/MNCAATourneySeeds.csv")
seeds.head()

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [614]:
seed_clean = seeds.copy()
seed_clean['Seed'] = seed_clean['Seed'].str.replace(r'[a-zA-Z]', '', regex=True).astype(int)
seed_clean = seed_clean[['Season', 'TeamID', 'Seed']]
seed_clean.head()

   Season  TeamID  Seed
0    1985    1207     1
1    1985    1210     2
2    1985    1228     3
3    1985    1260     4
4    1985    1374     5

In [615]:
if (seed_clean['Seed'] <= 16).all() and (seed_clean['Seed'] >= 1).all():
    print("All seed values are valid (between 1 and 16).")

All seed values are valid (between 1 and 16).

In [616]:
print(seed_clean.shape)
seed_clean

(2626, 3)

      Season  TeamID  Seed
0       1985    1207     1
1       1985    1210     2
2       1985    1228     3
3       1985    1260     4
4       1985    1374     5
...      ...     ...   ...
2621    2025    1161    12
2622    2025    1213    13
2623    2025    1423    14
2624    2025    1303    15
2625    2025    1313    16

[2626 rows x 3 columns]

## Step 3: Build Rankings Table (Massey)

In [617]:
massey = pd.read_csv("../data/raw/MMasseyOrdinals.csv")
massey.head()

   Season  RankingDayNum SystemName  TeamID  OrdinalRank
0    2003             35        SEL    1102          159
1    2003             35        SEL    1103          229
2    2003             35        SEL    1104           12
3    2003             35        SEL    1105          314
4    2003             35        SEL    1106          260

In [618]:
massey_clean = massey.copy()
massey_clean = massey_clean[(massey_clean['RankingDayNum'] == 133) & massey_clean['SystemName'].isin(['POM', 'SAG', 'MOR', 'DUN'])].reset_index(drop=True)
massey_clean = massey_clean[['Season', 'TeamID', 'SystemName', 'OrdinalRank']]      
massey_clean.head()

   Season  TeamID SystemName  OrdinalRank
0    2003    1102        DUN           97
1    2003    1103        DUN          165
2    2003    1104        DUN           43
3    2003    1105        DUN          306
4    2003    1106        DUN          305

In [619]:
massey_pivot = massey_clean.pivot(index = ['Season', 'TeamID'], columns = 'SystemName', values = 'OrdinalRank').reset_index()
massey_pivot.columns.name = None
massey_pivot.head()

   Season  TeamID    DUN    MOR    POM    SAG
0    2003    1102   97.0  132.0  160.0  149.0
1    2003    1103  165.0  139.0  163.0  172.0
2    2003    1104   43.0   26.0   33.0   37.0
3    2003    1105  306.0  309.0  307.0  312.0
4    2003    1106  305.0  294.0  263.0  268.0

In [620]:
massey_pivot.isnull().sum()

Season       0
TeamID       0
DUN       1358
MOR          0
POM          3
SAG        726
dtype: int64

In [621]:
# Cleaning up massey data
massey_pivot['DUN'] = massey_pivot.groupby('Season')['DUN'].transform(lambda x: x.fillna(x.median())) 
massey_pivot['MOR'] = massey_pivot.groupby('Season')['MOR'].transform(lambda x: x.fillna(x.median()))
massey_pivot['POM'] = massey_pivot.groupby('Season')['POM'].transform(lambda x: x.fillna(x.median()))
massey_pivot['SAG'] = massey_pivot.groupby('Season')['SAG'].transform(lambda x: x.fillna(x.median()))
massey_pivot.head()

   Season  TeamID    DUN    MOR    POM    SAG
0    2003    1102   97.0  132.0  160.0  149.0
1    2003    1103  165.0  139.0  163.0  172.0
2    2003    1104   43.0   26.0   33.0   37.0
3    2003    1105  306.0  309.0  307.0  312.0
4    2003    1106  305.0  294.0  263.0  268.0

In [622]:
massey_pivot.isnull().sum()

Season       0
TeamID       0
DUN       1358
MOR          0
POM          0
SAG        726
dtype: int64

In [623]:
massey_pivot.groupby('Season')['DUN'].count()

Season
2003    327
2004      0
2005      0
2006    334
2007    336
2008    341
2009    347
2010    347
2011    345
2012    345
2013    347
2014    351
2015      0
2016    351
2017    351
2018      0
2019    353
2021    347
2022    358
2023    363
2024    362
2025    364
Name: DUN, dtype: int64

In [624]:
massey_pivot.groupby('Season')['SAG'].count()

Season
2003    327
2004    326
2005    330
2006    334
2007    336
2008    341
2009    347
2010    347
2011    345
2012    345
2013    347
2014    351
2015    351
2016    351
2017    351
2018    351
2019    353
2021    347
2022    358
2023    363
2024      0
2025      0
Name: SAG, dtype: int64

In [625]:
#Handeling Missing Values in DUN
dun_median = massey_pivot.groupby('Season')['DUN'].median().sort_index().ffill()
print(dun_median)
season_medians = massey_pivot['Season'].map(dun_median)
massey_pivot['DUN'] = massey_pivot['DUN'].fillna(season_medians)
massey_pivot.isnull().sum()

Season
2003    164.0
2004    164.0
2005    164.0
2006    167.5
2007    168.5
2008    171.0
2009    174.0
2010    174.0
2011    173.0
2012    173.0
2013    174.0
2014    176.0
2015    176.0
2016    176.0
2017    176.0
2018    176.0
2019    177.0
2021    174.0
2022    179.5
2023    182.0
2024    181.5
2025    182.5
Name: DUN, dtype: float64

Season      0
TeamID      0
DUN         0
MOR         0
POM         0
SAG       726
dtype: int64

In [626]:
#Handeling Missing Values in SAG
sag_median = massey_pivot.groupby('Season')['SAG'].median().sort_index().ffill()
print(sag_median)
season_medians = massey_pivot['Season'].map(sag_median)
massey_pivot['SAG'] = massey_pivot['SAG'].fillna(season_medians)
massey_pivot.isnull().sum()

Season
2003    164.0
2004    163.5
2005    165.5
2006    167.5
2007    168.5
2008    171.0
2009    174.0
2010    174.0
2011    173.0
2012    173.0
2013    174.0
2014    176.0
2015    176.0
2016    176.0
2017    176.0
2018    176.0
2019    177.0
2021    174.0
2022    179.5
2023    182.0
2024    182.0
2025    182.0
Name: SAG, dtype: float64

Season    0
TeamID    0
DUN       0
MOR       0
POM       0
SAG       0
dtype: int64

In [627]:
print(massey_pivot.shape)
massey_pivot

(7627, 6)

      Season  TeamID    DUN    MOR    POM    SAG
0       2003    1102   97.0  132.0  160.0  149.0
1       2003    1103  165.0  139.0  163.0  172.0
2       2003    1104   43.0   26.0   33.0   37.0
3       2003    1105  306.0  309.0  307.0  312.0
4       2003    1106  305.0  294.0  263.0  268.0
...      ...     ...    ...    ...    ...    ...
7622    2025    1476  299.0  328.0  322.0  182.0
7623    2025    1477  353.0  298.0  330.0  182.0
7624    2025    1478  339.0  344.0  354.0  182.0
7625    2025    1479  290.0  312.0  342.0  182.0
7626    2025    1480  346.0  352.0  349.0  182.0

[7627 rows x 6 columns]

## Step 4: Build Tournament History Features

##### Seed Features

In [628]:
tourney_results = pd.read_csv("../data/raw/MNCAATourneyCompactResults.csv")
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [629]:
bracket_winners = tourney_results[['Season', 'WTeamID', 'DayNum']]
bracket_winners.rename(columns={'WTeamID': 'TeamID'}, inplace=True)

bracket_losers = tourney_results[['Season', 'LTeamID', 'DayNum']]
bracket_losers.rename(columns={'LTeamID': 'TeamID'}, inplace=True)

In [630]:
tourney_appearances = pd.concat([bracket_winners, bracket_losers], ignore_index=True)
tourney_appearances.head()

   Season  TeamID  DayNum
0    1985    1116     136
1    1985    1120     136
2    1985    1207     136
3    1985    1229     136
4    1985    1242     136

In [631]:
deepest_game = tourney_appearances.groupby(['Season', 'TeamID'])['DayNum'].max().reset_index()
deepest_game

      Season  TeamID  DayNum
0       1985    1104     144
1       1985    1112     137
2       1985    1116     138
3       1985    1120     144
4       1985    1130     143
...      ...     ...     ...
2552    2024    1443     137
2553    2024    1447     136
2554    2024    1450     138
2555    2024    1458     137
2556    2024    1463     139

[2557 rows x 3 columns]

In [632]:
conditions = [
    deepest_game['DayNum'] == 154,
    deepest_game['DayNum'] == 152,
    (deepest_game['DayNum'] >= 145) & (deepest_game['DayNum'] < 152),
    (deepest_game['DayNum'] >= 143) & (deepest_game['DayNum'] < 145),
    (deepest_game['DayNum'] >= 138) & (deepest_game['DayNum'] < 143),
    (deepest_game['DayNum'] >= 134) & (deepest_game['DayNum'] < 138),
    deepest_game['DayNum'] < 134
]

values = [6, 5, 4, 3, 2, 1, 0]

deepest_game['Round'] = np.select(conditions, values, default=0)
deepest_game

      Season  TeamID  DayNum  Round
0       1985    1104     144      3
1       1985    1112     137      1
2       1985    1116     138      2
3       1985    1120     144      3
4       1985    1130     143      3
...      ...     ...     ...    ...
2552    2024    1443     137      1
2553    2024    1447     136      1
2554    2024    1450     138      2
2555    2024    1458     137      1
2556    2024    1463     139      2

[2557 rows x 4 columns]

In [633]:
# Verifying the distribution of rounds
print(deepest_game['Round'].value_counts())
print(deepest_game['Round'].max())

Round
1    1294
2     639
3     304
4     164
6      78
5      78
Name: count, dtype: int64
6

In [634]:
all_teams = deepest_game['TeamID'].unique()
all_seasons = deepest_game['Season'].unique()
possible_indices = pd.MultiIndex.from_product([all_seasons, all_teams], names=['Season', 'TeamID'])
possible_indices = possible_indices.to_frame(index=False)

In [635]:
tournament_history = pd.merge(possible_indices, deepest_game, on=['Season', 'TeamID'], how='left')
tournament_history = tournament_history.fillna({'Round': 0})
tournament_history

       Season  TeamID  DayNum  Round
0        1985    1104   144.0    3.0
1        1985    1112   137.0    1.0
2        1985    1116   138.0    2.0
3        1985    1120   144.0    3.0
4        1985    1130   143.0    3.0
...       ...     ...     ...    ...
12046    2024    1202     NaN    0.0
12047    2024    1244     NaN    0.0
12048    2024    1182   138.0    2.0
12049    2024    1212   137.0    1.0
12050    2024    1391   137.0    1.0

[12051 rows x 4 columns]

In [636]:
tournament_history['round_last_year'] = tournament_history.groupby('TeamID')['Round'].shift(1)
tournament_history['round_avg_3yr'] = tournament_history.groupby('TeamID')['Round'].transform(lambda x: x.shift(1).rolling(window = 3, min_periods = 1).mean())
tournament_history['appearances_5yr'] = tournament_history.groupby('TeamID')['Round'].transform(lambda x: x.shift(1).rolling(window = 5, min_periods = 1).apply(lambda x: (x > 0).sum()))   
tournament_history

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
0,1985,1104,144.0,3.0,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0

In [637]:
# Verifying the new features for a specific team (Duke my school & the best school OAT :))
tournament_history[tournament_history['TeamID'] == 1181]

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
7,1985,1181,139.0,2.0,NaN,NaN,NaN
316,1986,1181,154.0,6.0,2.0,2.000000,1.0
625,1987,1181,144.0,3.0,6.0,4.000000,2.0
934,1988,1181,152.0,5.0,3.0,3.666667,3.0
1243,1989,1181,152.0,5.0,5.0,4.666667,4.0
1552,1990,1181,154.0,6.0,5.0,4.333333,5.0
1861,1991,1181,154.0,6.0,6.0,5.333333,5.0
2170,1992,1181,154.0,6.0,6.0,5.666667,5.0
2479,1993,1181,138.0,2.0,6.0,6.000000,5.0
2788,1994,1181,154.0,6.0,2.0,4.666667,5.0
3097,1995,1181,NaN,0.0,6.0,4.666667,5.0
3406,1996,1181,136.0,1.0,0.0,2.666667,4.0
3715,1997,1181,139.0,2.0,1.0,2.333333,4.0
4024,1998,1181,146.0,4.0,2.0,1.000000,4.0
4333,1999,1181,154.0,6.0,4.0,2.333333,4.0
4642,2000,1181,144.0,3.0,6.0,4.000000,4.0
4951,2001,1181,154.0,6.0,3.0,4.333333,5.0
5260,2002,1181,143.0,3.0,6.0,5.000000,5.0
5569,2003,1181,143.0,3.0,3.0,4.000000,5.0
5878,2004,1181,152.0,5.0,3.0,4.000000,5.0
6187,2005,1181,144.0,3.0,5.0,3.666667,5.0
6496,2006,1181,143.0,3.0,3.0,3.666667,5.0
6805,2007,1181,136.0,1.0,3.0,3.666667,5.0
7114,2008,1181,138.0,2.0,1.0,2.333333,5.0
7423,2009,1181,143.0,3.0,2.0,2.000000,5.0
7732,2010,1181,154.0,6.0,3.0,2.000000,5.0
8041,2011,1181,143.0,3.0,6.0,3.666667,5.0
8350,2012,1181,137.0,1.0,3.0,4.000000,5.0
8659,2013,1181,146.0,4.0,1.0,3.333333,5.0
8968,2014,1181,137.0,1.0,4.0,2.666667,5.0
9277,2015,1181,154.0,6.0,1.0,2.000000,5.0
9586,2016,1181,143.0,3.0,6.0,3.666667,5.0
9895,2017,1181,139.0,2.0,3.0,3.333333,5.0
10204,2018,1181,146.0,4.0,2.0,3.666667,5.0
10513,2019,1181,146.0,4.0,4.0,3.000000,5.0
10822,2021,1181,NaN,0.0,4.0,3.333333,5.0
11131,2022,1181,152.0,5.0,0.0,2.666667,4.0
11440,2023,1181,138.0,2.0,5.0,3.000000,4.0
11749,2024,1181,146.0,4.0,2.0,2.333333,4.0

In [638]:
print(tournament_history.shape)
tournament_history

(12051, 7)

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr
0,1985,1104,144.0,3.0,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0

##### Winner Each Year Feature

In [639]:
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [640]:
champions = tourney_results[['Season', 'WTeamID', 'DayNum']][tourney_results['DayNum'] == 154]
champions.rename(columns={'WTeamID': 'TeamID'}, inplace=True)
champions['won_championship_last_year'] = 1
champions['Season'] += 1
champions.head()
champions.shape

(39, 4)

In [641]:
champions.drop(columns=['DayNum'], inplace=True)
tournament_history = pd.merge(tournament_history, champions, on=['Season', 'TeamID'], how='left')
tournament_history = tournament_history.fillna({'won_championship_last_year': 0})
tournament_history
tournament_history.shape

(12051, 8)

In [642]:
# Verifying the new feature for a specific team (again Duke :) )
tournament_history[tournament_history['Season'].isin([1991,1992,1993]) & (tournament_history['TeamID'] == 1181)]

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year
1861,1991,1181,154.0,6.0,6.0,5.333333,5.0,0.0
2170,1992,1181,154.0,6.0,6.0,5.666667,5.0,1.0
2479,1993,1181,138.0,2.0,6.0,6.000000,5.0,1.0

In [643]:
print(tournament_history.shape)
tournament_history

(12051, 8)

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year
0,1985,1104,144.0,3.0,NaN,NaN,NaN,0.0
1,1985,1112,137.0,1.0,NaN,NaN,NaN,0.0
2,1985,1116,138.0,2.0,NaN,NaN,NaN,0.0
3,1985,1120,144.0,3.0,NaN,NaN,NaN,0.0
4,1985,1130,143.0,3.0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0,0.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0,0.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0,0.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0,0.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0,0.0

## Step 5: Merging All Features

In [644]:
#tournament_history = pd.merge(tournament_history, champions, on=['Season', 'TeamID'], how='left')
#tournament_history = tournament_history.fillna({'won_championship_last_year': 0})

team_features = pd.merge(tournament_history, season_averages, on=['Season', 'TeamID'], how='left')
team_features = pd.merge(team_features, seed_clean, on=['Season', 'TeamID'], how='left')
team_features = pd.merge(team_features, massey_pivot, on=['Season', 'TeamID'], how='left')

print(team_features.shape)
team_features.isnull().sum()

(12051, 27)

Season                           0
TeamID                           0
DayNum                        9494
Round                            0
round_last_year                309
round_avg_3yr                  309
appearances_5yr                309
won_championship_last_year       0
Score                         5648
OppScore                      5648
FGM                           5648
FGA                           5648
FGM3                          5648
FGA3                          5648
FTM                           5648
FTA                           5648
Ast                           5648
TO                            5648
Stl                           5648
Blk                           5648
PF                            5648
Win                           5648
Seed                          9493
DUN                           5648
MOR                           5648
POM                           5648
SAG                           5648
dtype: int64

In [645]:
team_features

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,OppScore,...,TO,Stl,Blk,PF,Win,Seed,DUN,MOR,POM,SAG
0,1985,1104,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12046,2024,1202,NaN,0.0,2.0,0.666667,1.0,0.0,78.833333,76.700000,...,11.033333,6.900000,2.666667,16.266667,0.500000,NaN,152.0,201.0,141.0,182.0
12047,2024,1244,NaN,0.0,1.0,0.333333,1.0,0.0,81.535714,83.714286,...,11.928571,7.142857,4.000000,20.785714,0.428571,NaN,236.0,264.0,263.0,182.0
12048,2024,1182,138.0,2.0,0.0,0.000000,0.0,0.0,70.058824,66.588235,...,11.352941,7.470588,4.382353,17.264706,0.676471,11.0,76.0,81.0,86.0,182.0
12049,2024,1212,137.0,1.0,0.0,0.000000,0.0,0.0,65.129032,68.870968,...,12.741935,7.129032,3.096774,16.161290,0.548387,16.0,238.0,298.0,267.0,182.0
12050,2024,1391,137.0,1.0,0.0,0.000000,0.0,0.0,74.483871,75.129032,...,10.064516,4.903226,2.967742,15.193548,0.612903,16.0,168.0,198.0,218.0,182.0

## Step 6: Creating table with proper features and target varible aligned

In [646]:
tourney_results = pd.read_csv("../data/raw/MNCAATourneyCompactResults.csv")
tourney_results.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [647]:
matchups = tourney_results.copy()
np.random.seed(1) # Setting a seed for reproducibility
matchups['random_team'] = np.random.choice([True, False], size = len(matchups))
matchups.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT  random_team
0    1985     136     1116      63     1234      54    N      0        False
1    1985     136     1120      59     1345      58    N      0        False
2    1985     136     1207      68     1250      43    N      0         True
3    1985     136     1229      58     1425      55    N      0         True
4    1985     136     1242      49     1325      38    N      0        False

In [648]:
matchups['TeamA_Id'] = np.where(matchups['random_team'], matchups['WTeamID'], matchups['LTeamID'])
matchups['TeamB_Id'] = np.where(matchups['random_team'], matchups['LTeamID'], matchups['WTeamID'])
matchups['Results'] = np.where(matchups['random_team'], 1, 0)
# Cleaning up the matchups data
matchups_cleaned = matchups[['Season', 'DayNum', 'TeamA_Id', 'TeamB_Id', 'Results']]
matchups.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,random_team,TeamA_Id,TeamB_Id,Results
0,1985,136,1116,63,1234,54,N,0,False,1234,1116,0
1,1985,136,1120,59,1345,58,N,0,False,1345,1120,0
2,1985,136,1207,68,1250,43,N,0,True,1207,1250,1
3,1985,136,1229,58,1425,55,N,0,True,1229,1425,1
4,1985,136,1242,49,1325,38,N,0,False,1325,1242,0

In [649]:
team_features.head()

,Season,TeamID,DayNum,Round,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,OppScore,...,TO,Stl,Blk,PF,Win,Seed,DUN,MOR,POM,SAG
0,1985,1104,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN
1,1985,1112,137.0,1.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
2,1985,1116,138.0,2.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
3,1985,1120,144.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
4,1985,1130,143.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN

In [650]:
final_features = pd.merge(matchups_cleaned, team_features, left_on = ['Season', 'TeamA_Id'], right_on = ['Season', 'TeamID'], suffixes = ('', '_A'), how='left')
final_features = pd.merge(final_features, team_features, left_on = ['Season', 'TeamB_Id'], right_on = ['Season', 'TeamID'], suffixes = ('', '_B'), how='left')
final_features.head()

,Season,DayNum,TeamA_Id,TeamB_Id,Results,TeamID,DayNum_A,Round,round_last_year,round_avg_3yr,...,TO_B,Stl_B,Blk_B,PF_B,Win_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B
0,1985,136,1234,1116,0,1234,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,1345,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,1207,154.0,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,1229,138.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,1325,136.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN

In [651]:
show_columns(final_features)

Season
DayNum
TeamA_Id
TeamB_Id
Results
TeamID
DayNum_A
Round
round_last_year
round_avg_3yr
appearances_5yr
won_championship_last_year
Score
OppScore
FGM
FGA
FGM3
FGA3
FTM
FTA
Ast
TO
Stl
Blk
PF
Win
Seed
DUN
MOR
POM
SAG
TeamID_B
DayNum_B
Round_B
round_last_year_B
round_avg_3yr_B
appearances_5yr_B
won_championship_last_year_B
Score_B
OppScore_B
FGM_B
FGA_B
FGM3_B
FGA3_B
FTM_B
FTA_B
Ast_B
TO_B
Stl_B
Blk_B
PF_B
Win_B
Seed_B
DUN_B
MOR_B
POM_B
SAG_B

In [652]:
# Cleaning up final_features
final_features = final_features.drop(columns=['TeamID', 'TeamID_B', 'DayNum_A', 'DayNum_B', 'Round', 'Round_B'], errors='ignore')
final_features.head()

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,TO_B,Stl_B,Blk_B,PF_B,Win_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B
0,1985,136,1234,1116,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN

In [653]:
show_columns(final_features)

Season
DayNum
TeamA_Id
TeamB_Id
Results
round_last_year
round_avg_3yr
appearances_5yr
won_championship_last_year
Score
OppScore
FGM
FGA
FGM3
FGA3
FTM
FTA
Ast
TO
Stl
Blk
PF
Win
Seed
DUN
MOR
POM
SAG
round_last_year_B
round_avg_3yr_B
appearances_5yr_B
won_championship_last_year_B
Score_B
OppScore_B
FGM_B
FGA_B
FGM3_B
FGA3_B
FTM_B
FTA_B
Ast_B
TO_B
Stl_B
Blk_B
PF_B
Win_B
Seed_B
DUN_B
MOR_B
POM_B
SAG_B

In [654]:
final_features['Season'].value_counts().sort_index()

Season
1985    63
1986    63
1987    63
1988    63
1989    63
1990    63
1991    63
1992    63
1993    63
1994    63
1995    63
1996    63
1997    63
1998    63
1999    63
2000    63
2001    64
2002    64
2003    64
2004    64
2005    64
2006    64
2007    64
2008    64
2009    64
2010    64
2011    67
2012    67
2013    67
2014    67
2015    67
2016    67
2017    67
2018    67
2019    67
2021    66
2022    67
2023    67
2024    67
Name: count, dtype: int64

### Final Features

In [655]:
final_features

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,TO_B,Stl_B,Blk_B,PF_B,Win_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B
0,1985,136,1234,1116,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN
1,1985,136,1345,1120,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
2,1985,136,1207,1250,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN
3,1985,136,1229,1425,1,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
4,1985,136,1325,1242,0,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,2024,146,1301,1181,1,1.0,0.333333,2.0,0.0,76.361111,...,9.375000,6.437500,3.656250,15.781250,0.750000,4.0,10.0,11.0,8.0,182.0
2514,2024,146,1397,1345,0,3.0,2.000000,5.0,0.0,79.468750,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0
2515,2024,152,1163,1104,1,6.0,3.000000,3.0,1.0,81.470588,...,11.812500,7.250000,4.062500,19.875000,0.656250,4.0,14.0,14.0,13.0,182.0
2516,2024,152,1301,1345,0,1.0,0.333333,2.0,0.0,76.361111,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0
2517,2024,154,1163,1345,1,6.0,3.000000,3.0,1.0,81.470588,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0

## Step 7: Train/Validation/Test Split

In [656]:
print('Results' in final_features.columns)
print(final_features['Season'].min(), final_features['Season'].max())

True
1985 2024

In [657]:
# Getting proper date range
final_features = final_features[(final_features['Season'] >= 2003) & (final_features['Season'] <= 2024)].reset_index(drop=True)
final_features

,Season,DayNum,TeamA_Id,TeamB_Id,Results,round_last_year,round_avg_3yr,appearances_5yr,won_championship_last_year,Score,...,TO_B,Stl_B,Blk_B,PF_B,Win_B,Seed_B,DUN_B,MOR_B,POM_B,SAG_B
0,2003,134,1411,1421,0,0.0,0.000000,0.0,0.0,72.800000,...,16.206897,7.068966,3.000000,19.103448,0.448276,16.0,241.0,277.0,273.0,251.0
1,2003,136,1436,1112,0,0.0,0.000000,0.0,0.0,67.793103,...,14.785714,8.464286,4.214286,17.750000,0.892857,1.0,9.0,4.0,3.0,2.0
2,2003,136,1113,1272,1,0.0,0.000000,0.0,0.0,75.965517,...,13.793103,7.379310,5.068966,18.758621,0.793103,7.0,19.0,23.0,20.0,24.0
3,2003,136,1141,1166,1,0.0,0.000000,0.0,0.0,79.344828,...,13.363636,8.393939,4.454545,17.272727,0.878788,6.0,27.0,33.0,27.0,18.0
4,2003,136,1143,1301,1,2.0,1.000000,2.0,0.0,74.482759,...,14.200000,7.766667,3.066667,18.666667,0.600000,9.0,23.0,31.0,48.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,2024,146,1301,1181,1,1.0,0.333333,2.0,0.0,76.361111,...,9.375000,6.437500,3.656250,15.781250,0.750000,4.0,10.0,11.0,8.0,182.0
1378,2024,146,1397,1345,0,3.0,2.000000,5.0,0.0,79.468750,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0
1379,2024,152,1163,1104,1,6.0,3.000000,3.0,1.0,81.470588,...,11.812500,7.250000,4.062500,19.875000,0.656250,4.0,14.0,14.0,13.0,182.0
1380,2024,152,1301,1345,0,1.0,0.333333,2.0,0.0,76.361111,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0
1381,2024,154,1163,1345,1,6.0,3.000000,3.0,1.0,81.470588,...,10.969697,5.666667,3.787879,14.363636,0.878788,1.0,3.0,6.0,3.0,182.0

In [658]:
# Separating and Defining the features and target variable
X = final_features.drop(columns=['Results', 'TeamA_Id', 'TeamB_Id', 'DayNum'])
y = final_features[['Season', 'Results']]

In [659]:
#Creating train, validation, and test sets
X_train = X[X['Season'] <= 2022].drop(columns=['Season'])
y_train = y[y['Season'] <= 2022].drop(columns=['Season'])

X_val = X[X['Season'] == 2023].drop(columns=['Season'])
y_val = y[y['Season'] == 2023].drop(columns=['Season']) 

X_test = X[X['Season'] == 2024].drop(columns=['Season'])
y_test = y[y['Season'] == 2024].drop(columns=['Season'])    

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((1248, 46), (1248, 1), (67, 46), (67, 1), (67, 46), (67, 1))

In [660]:
# Saving dataset to parquet files
X_train.to_parquet("../data/processed/X_train.parquet", engine='fastparquet')
X_val.to_parquet("../data/processed/X_val.parquet", engine='fastparquet')
X_test.to_parquet("../data/processed/X_test.parquet", engine='fastparquet')

y_train.to_parquet("../data/processed/y_train.parquet", engine='fastparquet')
y_val.to_parquet("../data/processed/y_val.parquet", engine='fastparquet')
y_test.to_parquet("../data/processed/y_test.parquet", engine='fastparquet')

print("Splits saved.")

Splits saved.